### ISSUE TITLE
Questions about the default IV

### ISSUE THREAD

**Issue by pulipulichen** [pvpoke/pvpoke#107]
Hi, PVPoke is the best tool for Pokemon Go PVP players. I want to use it to choose the best Pokemon in different IVs.

However, I found PVPoke use the default IV, which is different from the maximized overall IV.
For instance, Abomasnow's default IV is 5/14/11 and the maximized overall IV is 0/15/15 in greate league (maximized CP is 1500)
https://pvpoke.com/battle/

I have some question about the default IV.

1. How to determine the default IV?
2. Is the rankings calculated on the default IV?
https://pvpoke.com/rankings/

Thank you in advance.

**Comment by pvpoke** [comment]
Hey, thanks for the question.

1. Default IV's are automatically generated using an IV floor of 5. Pokemon that max above level 35 use an IV floor of 12 to emulate lucky trades. Default IV's end up around rank 250-500.

2. Correct, the rankings and all general battle simulations use the default IV's. If you go to the Settings page, you can set Pokemon to initialize at Rank 1 instead of using the default IV's (this won't affect the rankings however).

**Comment by pulipulichen** [comment]
I see. Thank you for the explanation.
