### ISSUE TITLE
Question: Shield usage

### ISSUE THREAD

**Issue by johndarv** [pvpoke/pvpoke#11]
Simming Kyogre vs TTar in Master League, I give them both 2 shields:

https://pvpoke.com/battle/10000/kyogre/tyranitar/22/023/012/

But the results only have 1 shield being used each (Kyogre has no shield on the first Crunch, and TTar doesn't shield the 2nd Thunder). I read the blurb about shield usage, and according to "Pokemon will always shield themselves if possible", I couldn't see a reason that the 2nd shield isn't used here. Is this a bug? Or am I missing something?

**Comment by pvpoke** [comment]
Thanks for posting! Just in case we're seeing different results, here's a screenshot of what I see at that link: [kyogre vs tyranitar](https://user-images.githubusercontent.com/46719444/52061413-d7777200-2533-11e9-8339-7cc7f3540389.PNG)

Kyogre shields one Crunch, Tyranitar shields one Thunder, and then Kyogre knocks out Tyranitar with Waterfall. Both Pokemon use one Charged Move and one shield, so that looks correct to me. Do you see something different?

**Comment by johndarv** [comment]
Oh! Sorry, right I see. No this is me being dumb then. I was misreading the graphic at the bottom (for some reason I thought charge moves were firing at the same time, and one was shielded and one wasn't - but now see that the shield graphic denotes shields to the charge move on the line above/below - which makes wayyyy more sense!).

Apologies, and thanks for the reply! Love the site and have signed up for Patreon. It's so nice to have something simple to come to to get a quick idea of a battle without having to enter IVs or anything like that :)
