### ISSUE TITLE
Is this an error or by design? Winning by 1hp is showing as a loss and 'close win' for the other pokemon

### ISSUE THREAD

**Issue by paulwongx** [pvpoke/pvpoke#131]
Link: https://pvpoke.com/team-builder/all/1500/machamp_shadow-17.5-13-13-13-4-4-1-m-1-6-2

When using the Team Builder and adding a Shadow Machamp with 13-13-13 stats, I click on the Altaria battle under 'Meta Scorecard' where it shows a Close Win for Altaria. However, when clicking the icon and viewing the actual battle... Shadow Machamp wins with 1 hp.

Is this by design or an oversight?

Thanks.

**Comment by XXVI-III-CX** [comment]
Unless something changed, and it appears they haven't, it isn't reliant purely on the 1-shield situation.

"Results are taken from 0 and 1 shield simulations." which means that even though shadow machamp technically wins in the 1 shield it loses the 0 shield outright. That's why it's a narrow win for altaria, because based on IVs it can lose the 1s.

**Comment by paulwongx** [comment]
> Unless something changed, and it appears they haven't, it isn't reliant purely on the 1-shield situation.
> 
> "Results are taken from 0 and 1 shield simulations." which means that even though shadow machamp technically wins in the 1 shield it loses the 0 shield outright. That's why it's a narrow win for altaria, because based on IVs it can lose the 1s.

That makes sense. Thanks for clarifying!
