### ISSUE TITLE
Galatians Rapidash chooses wrong moves and loses winnable match

### ISSUE THREAD

**Issue by magus** [pvpoke/pvpoke#193]
Galatians Rapidash in Psychic cup loses to Alolan Raichu

but it’s because Rapidash is for some reason continuing to use Body Slam even after baiting the shield

![D5EE9CC9-2C8A-49AE-B933-3C7618A1C28B](https://user-images.githubusercontent.com/290084/189501801-b8d890ca-268d-440c-b5e9-f74a82a5a87d.jpeg)

> https://pvpoke.com/battle/1500/rapidash_galarian-22-8-15-15-4-4-1-1/raichu_alolan/11/0-2-1/2-4-3/

if you sandbox and manually Megahorn you win, I wonder if this is impacting other battles

![57A67194-9D91-469A-86B4-F91DC3F22879](https://user-images.githubusercontent.com/290084/189501868-0b16b511-ff4c-48b0-ae92-ad0742c5c6e6.jpeg)

> https://pvpoke.com/battle/sandbox/1500/rapidash_galarian-22-8-15-15-4-4-1-1/raichu_alolan/22/0-2-1/2-4-3/13.111100-14.101100-21.100000/

**Comment by pvpoke** [comment]
Hey magus, thanks for posting! It looks like Alolan Raichu reaches Thunder Punch and KO's Rapidash before it reaches Megahorn. In your sandbox example, Rapidash reaches Megahorn because Alolan Raichu isn't throwing the Thunder Punch.

![image](https://user-images.githubusercontent.com/46719444/189528997-623492ef-9743-492b-8a0f-99bb0e9245c8.png)

https://pvpoke.com/battle/sandbox/1500/rapidash_galarian-22-8-15-15-4-4-1-1/raichu_alolan/22/0-2-1/2-4-3/13.111100-14.101100-19.111000/
