### ISSUE TITLE
Hisui cup rankings have invalid pokemon

### ISSUE THREAD

**Issue by CobaltFrost** [pvpoke/pvpoke#262]
The following pokemon are legal:

"Only Pokémon first discovered in the Hisui region or Pokémon with a Pokédex number from #387 to #493 will be allowed."

For example, pvpoke says lickitung is valid, but can't be added to hisui cup teams in game.

**Comment by theGOTOguy** [comment]
I have included appropriate filters for the current Hisui Cup in #263. 

You may have to use the "exclude" filter to specify rather than "include" if the [default filters](https://github.com/pvpoke/pvpoke/blob/c8e77de4ea7adc4e67c609c7492c39c41af4a685/src/data/gamemaster/cups/hisui.json) exhibit the same bug described for Custom Cup in #263.

**Comment by pvpoke** [comment]
Sorry for the delay, I have Hisui Cup updated with the changed ruleset.
