### ISSUE TITLE
Cross Chop isn't used when it should be

### ISSUE THREAD

**Issue by AlbertKleinstein** [pvpoke/pvpoke#3]
https://pvpoke.com/battle/1500/machamp/poliwrath/00/132/013/

Here I expect Machamp to use Cross Chop after 5 Counters (7 energy x 5 = 35 energy, needed for Cross Chop).

Not sure why Machamp here still uses fast moves until fainting.

**Comment by AlbertKleinstein** [comment]
This was really hard to find, thank you for finding out the root cause and fixing it.

Great work!

**Comment by pvpoke** [comment]
This was a monster of a bug to solve but I ran additional tests and the updates in v1.1.0 didn't solve this issue for every matchup. I ended up rewriting how Pokemon anticipate when they will faint and when they will use Charged Moves as a result. Happy to report this is now fixed for real!

**Comment by AlbertKleinstein** [comment]
There is still a problem here:
https://pvpoke.com/battle/1500/medicham/skarmory/22/012/031/

When Medicham has Ice Punch and Psychic, there is (correctly) a simultaneous knockout.
However, when Medicham has Ice Punch and Dynamic Punch, it doesn't use the 3rd Ice Punch even after 7 Counters and it faints on Air Slashes.

**Comment by pvpoke** [comment]
Thanks for following up on this, I've reopened the issue. I looked into it and it appears Medicham isn't correctly evaluating that Skarmory will use Air Slash before its next action. A simple change in ceiling a value involved in this evaluation instead of flooring it fixes this particular matchup.

Now the only question is, does this break any other matchups? ;)

I'll have this fix launched in the next release. In the meantime, somewhat off topic, something that could be extremely helpful for debugging purposes is a battle log that highlights each Pokemon's decision making on its turn; what it evalutes, what it chooses to do or not do, etc.
