### ISSUE TITLE
AI opponents charging way past 100 energy and losing battles they should win

### ISSUE THREAD

**Issue by Orangegrarrl89** [pvpoke/pvpoke#65]
A few of my pvpoke training battles the past couple days have involved AI opponents charging way past 100 energy and losing battles they should win.  I noticed it a bunch of times in great league training last night when using a Vigoroth against the AI's Azumarill where the Azumarill would use 12-16 Bubbles before using a charge move, thus losing 32-66 of energy after capping at 100 with the result being that my Vigoroth would win the battle even though it should lose.  I noticed it again just now in master league training when my Dialga battled against the AI's Mewtwo, and the Mewtwo used 15 Pyscho Cuts before throwing a charge move, thus losing 35 energy after capping at 100, not being able to get to a second charge move, and losing to my Dialga in the 1x1 shield even though it should win that battle.  In general the past couple of days it seems like AI opponents have been charging much longer before throwing charge moves, but these are extreme examples where it is changing the outcome. (Love the site by the way, been using it for quite a while, and it is enormously helpful.)

**Comment by pvpoke** [comment]
Hey, thanks so much for the report! I looked into it this morning and resolved what was causing the problem.

When I made adjustments to Pokemon detecting when they're about to faint last week, I added a snippet that turned off farm behavior when Pokemon are close to fainting. The intention was to switch the farming behavior off so Pokemon fire their Charged Moves before fainting - however, and this was pretty silly on my part - it messed with how the AI evaluates the current battle scenario and determines if it can farm or not. Because Pokemon in the sims were firing Charged Moves with farming turned on, the AI thought it could farm in scenarios it couldn't. Let me know if you run into any other problems!
